version: 2

models:
  - name: stg_worldbank
    description: "World Bank data. One row per country per indicator per year."
    columns:
      - name: indicator_code
        data_tests:
          - not_null
      - name: country_code
        description: "ISO3 country code"
        data_tests:
          - not_null
      - name: observation_year
        data_tests:
          - not_null

  - name: stg_imf
    description: "IMF data. One row per country per indicator per year."
    columns:
      - name: indicator_code
        data_tests:
          - not_null
      - name: country_code
        description: "ISO3 country code"
        data_tests:
          - not_null
      - name: observation_year
        data_tests:
          - not_null
          
  - name: stg_undp
    description: "UNDP HDR data. One row per country per indicator per year."
    columns:
      - name: indicator_code
        data_tests:
          - not_null
      - name: country_code
        description: "ISO3 country code"
        data_tests:
          - not_null
      - name: observation_year
        data_tests:
          - not_null