# CI pipeline for the FRED Economic Indicators Pipeline
# Will run automatically on every push and pull request to main but only when files inside fred-data-pipeline/ are changed

name: FRED_CI
on:
  push:
    branches: [main]
    paths:
      - 'fred-data-pipeline/**'
      - '.github/workflows/fred-data-pipeline-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'fred-data-pipeline/**'
      - '.github/workflows/ci.yml'

jobs:
  python_job:  # checking for syntax errors, unused imports, undefined variables, style issues
    name: python_lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  # check code onto runner so the codes can be accessed
        uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ruff
        run: pip install ruff==0.4.4

      - name: Run ruff  # run the link checks on the codes in below paths
        run: ruff check fred-data-pipeline/src/ fred-data-pipeline/dags/ --select F
  
  dbt_job:  # check for invalid sql, syntax error, bad jinja templating
    name: dbt_compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dbt
        run: pip install dbt-snowflake==1.11.3

      - name: Create dbt profiles.yml  # temporary file to simulate dbt connection to snowflake for check to happen. no actual connection takes place
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << 'EOF'
          fred_data_pipeline:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: dummy_value
                user: dummy_value
                password: dummy_value
                role: dummy_value
                warehouse: dummy_value
                database: FRED_DB
                schema: STAGING
                threads: 1
          EOF

      - name: Run dbt compile   
        run: |
          cd fred-data-pipeline/dbt_project/fred_data_pipeline
          dbt compile --profiles-dir ~/.dbt --project-dir .


      
